<?php $orderData = $block->getOrderData() ?>

<ul>
    <?php foreach ($orderData as $key => $value): ?>
        <?php if ($key == 'items'): ?>
            <ul>
                <?php foreach ($value as $itemValue): ?>
                    <?php foreach($itemValue as $itemKey => $item): ?>
                        <li><?php echo $itemKey ?> : <?php echo $item ?></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <li><?php echo $key ?> : <?php echo $value ?></li>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
