<?php
/**
 * {Description}
 *
 * @category    Wcb
 * @package     Wcb_
 * @contact     Ryan Street <rstreet@wcbradley.com>
 */

namespace Training\Basics\Logger;


use Magento\Framework\App\State;
use Magento\Framework\Logger\Monolog;

class Log extends Monolog {

    /**
     * @var State
     */
    private $state;

    public function __construct(
        $name,
        $handlers = array(),
        $processors = array(),
        State $state
    ) {
        parent::__construct( $name, $handlers, $processors );
        $this->state = $state;
    }

    public function addRecord( $level, $message, array $context = [] ) {
        if($this->state->getMode() == State::MODE_DEVELOPER) {
            // echo out errors here....
        }
        return parent::addRecord( $level, $message, $context ); // TODO: Change the autogenerated stub
    }
}